# Práctica 2.

## Diccionarios

Escribir un programa que almacene las calificaciones de un semestre en el diccionario {'Electromagnetismo': 10, 'Electrónica': 9, 'Relatividad': 8,'Física Computacional': 10, 'Física Estadística': 9,} y después muestre por pantalla las calificaciones de cada asignatura en el formato *asignatura* como Key y *calificacion* como valor del Key. Al final debe mostrar también el promedio del semestre.


In [ ]:
#Tu código
diccionario={'Electromagnetismo':10,'Electrónica': 9, 'Relatividad': 8,'Física Computacional': 10, 'Física Estadística': 9}


for i,j in diccionario.items():
    print(f"{i}: {j}")

Electromagnetismo: 10
Electrónica: 9
Relatividad: 8
Física Computacional: 10
Física Estadística: 9


In [ ]:
#calcular el promedio
a=0
for i in diccionario:
  a+=diccionario.get(i)
print ("El promedio es:",a/len(diccionario))




El promedio es: 9.2


## Programa básico de Python

Un satélite se encuentra en una órbita circular alrededor de la Tierra, tal que completa un círculo en $T$ segundos, $T$ es el periodo de la órbita:

i) Muestra que la altitud $h$ sobre la superficie de la Tierra será:
$$
h=\left( \frac{GMT^2}{4\pi^2} \right)^{\tfrac{1}{3}} -R
$$
donde $G$ es la constante de gravitación universal con valor $G=6.67\times10^{-11}$ m$^{3}$kg$^{-1}$s$^{-2}$, $M$ es la masa de la Tierra $M=5.97\times10^{24}$kg y $R$ es el radio de la Tierra $R=6371$ kg.

(ii) Escribe un programa que le pregunte al usuario el periodo que desea tenga su satélite girando alrededor de la Tierra y el programa le regrese la altitud, en metros, que deberá tener.

(iii) ¿Qué altitud deberá tener el satélite su queremos que orbite la Tierra con un periodo de un día (órbita geosíncrona), 90 minutos, 45 minutos? ¿Qué observas?

(iv) En práctica, una órbita geosíncrona es aquella cuya órbita tiene un periodo de un día sideral, que es de 23.93 horas, no de 24 horas. ¿Por qué es esto? ¿Cuál será la diferencia en altitud entre $T$= 23.93 horas y $T$= 24 horas.


In [ ]:
# Tu código

#ii)
from math import *
G= 6.67e-11
M=5.97e24
R=6371e3
h=0


def h(T):
  t=T*3600
  h= -R+((G*M*(t**2))/(4*(pi)**2))**(1/3)
  return h

T=float(input("ingresa el periodo en horas: "))
print('La altura es:',h(T))



ingresa el periodo en horas: 24
La altura es: 35855910.176174976


In [ ]:
# iii) tiempo 90 minutos/60 minutos=1.5 h
h(1.5)


279321.6253728606

In [ ]:
# tiempo 45 minutos/60 minutos=.75 h
h(.75)

-2181559.8978108233

In [ ]:
#Tiempo 24 horas
h(24)


35855.91017617498

In [ ]:
#Tiempo 23.93 horas
h(23.93)

35773762.329895645

In [ ]:
#Calculo de la diferencia
diferencia= h(24)-h(23.93)
print(diferencia)

82147.84627933055


## Matriz de Vandermonde

Considera la matriz de Vandermonde, la cual se define como

$$
A_{ij} = v_i^{j-1} \;\;\; i=0,1,2, \cdots, n; \;\;\; j=0,1,2,\cdots, n
$$

Crea una función llamada *Vandermonde(v)* que reciba un vector $\vec{v}$ y regrese la matriz A definida arriba.


In [ ]:
# Tu código
import numpy as np
def Vandermonde(v):
  n = len(v)
  A = np.zeros([n,n], float)
  for i in range(n):
    for j in range(n):
      A[i,j] = v[j] ** i
  return A



In [ ]:
v = [1, 2, 3, 4]
Vandermonde(v)


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  9., 16.],
       [ 1.,  8., 27., 64.]])

## Matriz tridiagonal

Crea una función llamada tridiagonal que reciba un vector y regrese la matriz cuadrada

$$
A=
\begin{bmatrix}
v_{0} & v_{1}^2 & 0 &  0 & 0 & \dots  & 0 \\
v_{1}^3 & v_{1} & v_{2}^2 &  0 & 0 & \dots  & 0 \\
0 & v_{2}^3 & v_2 &  v_{3}^2 & 0 & \dots  & 0 \\
0 & 0 & v_3^2 &  v_{3} & v_4^2 & \dots  & 0 \\
\dots & \dots  & \dots & \dots & \dots & \dots & \dots\\
0 & 0 & 0 & \dots & v_{n-1}^3 & v_{n-1}  & v_{n}^2 \\
0 & 0 & 0 & 0 & \dots & v_{n}^3  & v_{n} \\
\end{bmatrix}
$$


Prueba con varios vectores e incluye estos vectores en tu código.



In [ ]:
#Tu código


import numpy as np

def tridiagonal(v):

    n = len(v)
    A = np.zeros([n, n], int)
    for i in range(n):
        for j in range(n):
            if i == j:
                A[i, j] = v[i]
            elif i == j + 1:
                A[i, j] = v[i] ** 3
            elif i == j-1:
                A[i, j] = v[i+1] ** 2
            else:
                A[i, j] = 0
    return A






In [ ]:
tridiagonal([1,2,3,4])

array([[ 1,  4,  0,  0],
       [ 8,  2,  9,  0],
       [ 0, 27,  3, 16],
       [ 0,  0, 64,  4]])

## Matriz de Pauli

Las matrices de Pauli son muy populares en Mecánica Cuántica. Se sabe que para una partícula con espín $\tfrac{1}{2}$, como es el electrón, las matrices de Pauli tienen la siguiente forma:

\begin{equation*}
\sigma_x=
\begin{bmatrix}
0&1\\
1&0
\end{bmatrix} \hspace{0.5cm}
\sigma_y=\begin{bmatrix}
0&-i\\
i&0
\end{bmatrix} \hspace{0.5cm}
\sigma_z=\begin{bmatrix}
1&0\\
0&-1
\end{bmatrix}
\end{equation*}

Haz una función llamada *Pauli* que reciba el eje y regrese la matriz de Pauli correspondiente, es decir, escribas *mx=Pauli('x')* y regrese $\sigma_x$.


In [ ]:
# Tu código

def Pauli(n):
  if n=='x':
    print(np.array([[0,1],[1,0]]))
  elif n=='y':
    print(np.array([[0, complex(0, -1)], [complex(0,1), 0]]))
  elif n=='z':
    print(np.array([[1,0],[0,-1]]))
  else:
    print('Digita una coordenada espacial correcta.')

In [ ]:
#Prueba del código
Pauli('x')
Pauli('y')
Pauli('z')
Pauli(2)

[[0 1]
 [1 0]]
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]
[[ 1  0]
 [ 0 -1]]
Digita una coordenada espacial correcta.


## Propiedades de las matrices de Pauli

Haremos 3 funciones para comprobar las propiedades más importantes de las matrices de Pauli.

* $\sigma_x^2=\sigma_y^2=\sigma_z^2=\begin{bmatrix}
1&0\\
0&1
\end{bmatrix}$.

Haz una función llamada *matriz\_al\_cuadrado*, que reciba una matriz y regrese su matriz al cuadrado. Ya que tengas tu función, prueba con las 3 matrices de Pauli, generadas en el problema anterior. Hint: Puedes reciclar el código de multiplicación de matrices.

* $Tr(\sigma_i)=0$.

Haz una función llamada traza que reciba una matriz y regrese su traza. Recuerda que la traza de una matriz cuadrada es la suma de los elementos de la diagonal.

* $det(\sigma_i)=-1.$

Haz una función que calcule el determinante de una matriz. Hint: Puedes usar el comando *numpy.linalg.det(M)*, importando *import numpy.linalg* para comprobar el determinante obtenido por tu código.

In [ ]:
# Tu código
def matriz_al_cuadrado(n):
  if n=='x':
    sigma_x=np.array([[0,1],[1,0]])
    sigmaxx=np.dot(sigma_x,sigma_x)
    print('La matriz al cuadrado es:',sigmaxx)
  elif n=='y':
    sigma_y=np.array([[0, complex(0, -1)], [complex(0,1), 0]])
    sigmayy=np.dot(sigma_y,sigma_y)
    print('La matriz al cuadrado es:',sigmayy)
  elif n=='z':
    sigma_z=np.array([[1,0],[0,-1]])
    sigmazz=np.dot(sigma_z,sigma_z)
    print('La matriz al cuadrado es:',sigmazz)
  else:
    print('Digita una coordenada espacial correcta.')


In [ ]:
matriz_al_cuadrado('z')

La matriz al cuadrado es: [[1 0]
 [0 1]]


In [ ]:
#Función traza
def traza(A):
    if len(A) != len(A[0]):
        print('No es posible calcular la traza de la matriz')
    else:
        Traza = 0
        for i in range(len(A)):
            for j in range(len(A[0])):
                if i == j:
                    Traza += A[i][j]
        return Traza




In [ ]:
traza([[11,0,2],[0,-1,1],[1,2,3]])

13

In [ ]:
traza([[11,0,2],[0,-2]])

No es posible calcular la traza de la matriz


In [ ]:
# Determinante de una matriz
#El deter

def determinante_matriz(A):

    matriz = np.array(A)
    determinante = np.linalg.det(matriz)

    return determinante

In [ ]:
determinante_matriz([[11,0,1],[0,2,3],[1,2,3]])

-1.9999999999999984

In [ ]:
def determinante(matrix):

    # Verifica que la matriz sea cuadrada
    n = len(matrix)
    if n == 0:
        raise ValueError("La matriz está vacía")
    for r in matrix:
        if len(r) != n:
            raise ValueError("La matriz no es cuadrada")


    if n == 1:
        return matrix[0][0]


    det = 0
    for j in range(n):

        cofactor = matrix[0][j] * determinante([r[:j] + r[j+1:] for r in matrix[1:]])

        det += (-1) ** j * cofactor

    return det




In [ ]:
determinante([[11,0,4],[0,2,3],[1,2,3]])

-8